language: go
go:
- 1.8

# Sólo vamos a manejar una rama máster, pero es buena práctica indicar sobre qué rama quieres operar
branches:
  only:
  - master

# Estas líneas sirven para instalar openssl y rsync antes de que empiece a ejecutar el script, harán falta
addons:
  apt:
    packages:
      - rsync
      - openssh-client

# Estas son las líneas que añadimos antes en el comando "--add", y que no tocaremos
before_install:
- openssl aes-256-cbc -K $encrypted_f665cd430f79_key -iv $encrypted_f665cd430f79_iv -in travis_access.enc -out travis_access -d

# en esta sección instalaremos los requisitos si los tenemos y sobre todo, las 4 últimas líneas son las importantes para gestionar la clave privada
install:
  - GOPATH=$HOME/go go get github.com/spf13/hugo
  - eval $(ssh-agent -s)
  - chmod 600 travis_access && ssh-add travis_access
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

# Generamos nuestro contenido estático
script:
  - "$HOME/go/bin/hugo"

# Y realizamos el rsync igual que antes
after_success:
  - rsync -avz --delete public/ $BLOG
